apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: csi-driver-monitoring
  labels:
    app: grafana
    app.kubernetes.io/part-of: csi-driver-observability
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.csi-driver-monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "60s"
          httpMethod: POST
